version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - API_KEY=kB4PnxuL9HV32Hf0oG8KbdyGcG39fNcU9Lw7wLkB6zIc  # Replace with your actual API key
    command: ["./start.sh"]  # Use start.sh script to run migrations and start FastAPI

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb-scripts:/docker-entrypoint-initdb.d  # Mount the SQL script directory for initialization
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: fastapi-celery
    command: celery -A app.tasks.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
